import React from "react"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

import Navbar from "@/app/layout/navbar/Navbar";
import AuthContextProvider from "@/app/contexts/auth-context";

import Username from "@/app/layout/userNav/UserNav";
import checkCookies from "@/app/utils/helpers";

export const metadata: Metadata = {
	title: 'General Armies',
	description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
	const name = await checkCookies('userName')
	const email = await checkCookies('userMail')
	const _id = await checkCookies('_id')

	return (
		<html lang="en">
		<body className={inter.className}>
		<AuthContextProvider auth={!!name && !!email}>
			<header>
				<Navbar />
				{name &&
					<Username user={name} email={email} _id={_id}/>
				}
			</header>
			{children}
		</AuthContextProvider>
		</body>
		</html>
	)
}
